// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG62-3WbaZuotAMLkBK7KvhZg3m6UPD98',
    appId: '1:934114202056:web:d8d352b823a53f67d530fd',
    messagingSenderId: '934114202056',
    projectId: 'smartcourierassistant',
    authDomain: 'smartcourierassistant.firebaseapp.com',
    storageBucket: 'smartcourierassistant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2Q81K24BNR5uFWdOfyWo7ndEdgD6ks0',
    appId: '1:934114202056:android:79fa0b69e184ff8dd530fd',
    messagingSenderId: '934114202056',
    projectId: 'smartcourierassistant',
    storageBucket: 'smartcourierassistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMnWQOehA8e1yQfBuVOQG1xykMcSUJ61c',
    appId: '1:934114202056:ios:dec507254cf04d5cd530fd',
    messagingSenderId: '934114202056',
    projectId: 'smartcourierassistant',
    storageBucket: 'smartcourierassistant.firebasestorage.app',
    iosBundleId: 'com.example.smartCourierAssistant',
  );
}
